name: Auto-update flake

on:
  schedule:
    - cron: "15 4 * * 1"
  workflow_dispatch: {}

jobs:
  update:
    runs-on: docker # your runner label
    container:
      image: nixos/nix:2.24.10 # Nix preinstalled
    steps:
      # Install Node for JS-based actions (e.g., checkout)
      - name: Install Node via Nix
        run: |
          set -euo pipefail
          nix --version
          nix profile install nixpkgs#nodejs_22
          echo "/root/.nix-profile/bin" >> "$GITHUB_PATH"   # make node visible to later steps
          node --version
          npm --version

      - name: Checkout
        uses: https://data.forgejo.org/actions/checkout@v4
        with:
          fetch-depth: 0

      # (optional) now JS actions will work since Node is on PATH
      # - uses: https://github.com/DeterminateSystems/nix-installer-action@v14

      - name: Update flake & check
        env:
          NIX_CONFIG: experimental-features = nix-command flakes
        run: |
          nix flake update
          git diff --quiet --exit-code flake.lock || nix flake check --show-trace --print-build-logs

      - name: Commit & push lockfile
        if: success() && !cancelled() && !failure()
        run: |
          if ! git diff --quiet --exit-code flake.lock; then
            git config user.name "Forgejo Actions"
            git config user.email "ci@local"
            git add flake.lock
            git commit -m "chore(flake): update inputs [skip ci]"
            git push
          fi
